apply plugin: "com.github.johnrengelman.shadow"

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    runConfigs.configureEach {
        it.ideConfigGenerated false
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

// fabricApi {
//     configureDataGeneration()
// }

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    // Remove the next line if you don't want to depend on the API
    // modImplementation "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    implementation(include("net.jodah:typetools:${rootProject.type_tools_version}"))

    implementation(include("com.github.BlockNeko-11.UnifiedConfig:unified-config-core:${rootProject.unified_config_version}"))
    implementation(include("com.github.BlockNeko-11.UnifiedConfig:unified-config-gson:${rootProject.unified_config_version}"))

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

def props = [
    "id": rootProject.mod_id,
    "version": project.version,
    "name": rootProject.mod_name,
    "description": rootProject.mod_description,
    "home_page": rootProject.mod_home_page,
    "sources_page": rootProject.mod_sources_page,
    "minecraft_dependency": rootProject.fabric_mcver_dependency
]

processResources {
    props.forEach { k, v ->
        inputs.property k, v
    }

    filesMatching("fabric.mod.json") {
        expand props
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
