# Gradle Settings
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

# Maven Metadata
archives_base_name=sunshine-core
maven_group=io.github.blockneko11

# Mod Metadata
mod_id=sunshinecore
mod_version=1.1.0
mod_name=Sunshine Core
mod_description=An api library for multi-loader mods.
mod_home_page=https://github.com/BlockNeko11
mod_sources_page=https://github.com/BlockNeko11/ShunshineCore

# Minecraft Settings
enabled_platforms=fabric,neoforge
minecraft_version=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_mcver_dependency=>=1.21 <1.21.2
fabric_loader_version=0.18.4
fabric_api_version=0.116.8+1.21.1

# FML
fml_mcver_dependency=[1.21, 1.21.2)

# Forge
# forge_version=47.4.3-1.20.1
# forge_dependency=[46, )

# NeoForge
neoforge_version=21.1.215
neoforge_dependency=[20, 22)

# Other deps
type_tools_version=0.6.3
