apply plugin: "com.github.johnrengelman.shadow"

architectury {
    platformSetupLoomIde()
    neoForge {
        platformPackage = "forge"
    }
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    runConfigs.configureEach {
        it.ideConfigGenerated false
    }

    // forge {
    //     convertAccessWideners = true
    //     extraAccessWideners.add loom.accessWidenerPath.get().asFile.name

    //     mixinConfig "nekocore.mixins.json"
    // }

    neoForge {}
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven {
        url = "https://maven.neoforged.net/releases/"
    }
}

dependencies {
    // forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    
    // Remove the next line if you don't want to depend on the API
    // modImplementation "dev.architectury:architectury-forge:${rootProject.architectury_version}"

    // implementation(include("com.github.BlockNeko-11.UnifiedConfig:unified-config-core:${rootProject.unified_config_version}"))
    // implementation(include("com.github.BlockNeko-11.UnifiedConfig:unified-config-gson:${rootProject.unified_config_version}"))
    // implementation(include("com.github.BlockNeko-11.UnifiedConfig:unified-config-snakeyaml:${rootProject.unified_config_version}"))

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }
}

def props = [
    "id": rootProject.mod_id,
    "version": project.version,
    "name": rootProject.mod_name,
    "description": rootProject.mod_description,
    "home_page": rootProject.mod_home_page,
    "sources_page": rootProject.mod_sources_page,
    "minecraft_dependency": rootProject.fml_mcver_dependency,
    "neoforge_dependency": rootProject.neoforge_dependency
]

processResources {
    props.forEach { k, v ->
        inputs.property k, v
    }

    filesMatching("META-INF/neoforge.mods.toml") {
        expand props
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
