modLoader = "javafml"
loaderVersion = "[0,)"
license = "Unlicensed"

[[mods]]
modId = "testmod"
version = "1.0.0"
displayName = "Test Mod"
authors = "Me!"
displayURL = "https://example.com"
description = '''
Test Mod
'''
logoFile = "icon.png"

[[dependencies.testmod]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "minecraft"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "sunshinecore"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "testmod.mixins.json"
